/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.Dimension;
import java.awt.Graphics;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DuongAli
 */
public class frmQuanLyNhanVien extends javax.swing.JFrame {

    String string = "src\\images\\QuanLyNhanVien.png";

    /**
     * Creates new form frmQuanLyNhanVien
     */
    public frmQuanLyNhanVien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jpnQuanLyNhanVien1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblQuanLyNhanVien = new javax.swing.JTable();
        jpnQuanLyNhanVien2 = new javax.swing.JPanel(){
            ImageIcon icon = new ImageIcon(string);
            public void paintComponent(Graphics g) {
                Dimension d = this.getSize();
                g.drawImage(icon.getImage(),0,0,d.width,d.height,null);
                setOpaque(false);
                super.paintComponent(g); }
        };
        lblMaNhaVien = new javax.swing.JLabel();
        lblSex = new javax.swing.JLabel();
        lblTenNhanVien = new javax.swing.JLabel();
        txtMaNhanVien = new javax.swing.JTextField();
        txtTenNhanVien = new javax.swing.JTextField();
        lblQuanLyNhanVien = new javax.swing.JLabel();
        txtBirthday = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        lblBirthday = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblSoCMND = new javax.swing.JLabel();
        txtSoCMND = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        lblPhone = new javax.swing.JLabel();
        lblDateStart = new javax.swing.JLabel();
        txtDateStart = new javax.swing.JTextField();
        lblPosition = new javax.swing.JLabel();
        lblTool = new javax.swing.JLabel();
        btnInsert = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        lblSearch = new javax.swing.JLabel();
        cbbPosition = new javax.swing.JComboBox<>();
        RdoBtnMale = new javax.swing.JRadioButton();
        RdoBtnFemale = new javax.swing.JRadioButton();
        jMenuQuanLyNhanVien = new javax.swing.JMenuBar();
        jMenuHome = new javax.swing.JMenu();
        jMenuSystem = new javax.swing.JMenu();
        jMenuSetting = new javax.swing.JMenu();
        jMenuHelf = new javax.swing.JMenu();
        jMenuInfo = new javax.swing.JMenu();
        jMenuLogOut = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jpnQuanLyNhanVien1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        tblQuanLyNhanVien.setBackground(new java.awt.Color(0, 0, 0));
        tblQuanLyNhanVien.setForeground(new java.awt.Color(0, 255, 255));
        tblQuanLyNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Nhân Viên", "Tên Nhân Viên", "Giới Tính", "Ngày Sinh", "Đia Chỉ", "Số CMND", "Số Điện Thoại", "Ngày Vào Làm", "Chức Vụ"
            }
        ));
        tblQuanLyNhanVien.setSelectionBackground(new java.awt.Color(222, 222, 222));
        tblQuanLyNhanVien.setSelectionForeground(new java.awt.Color(22, 22, 22));
        tblQuanLyNhanVien.setShowVerticalLines(false);
        tblQuanLyNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblQuanLyNhanVienMouseClicked(evt);
            }
        });
        tblQuanLyNhanVien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblQuanLyNhanVienKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblQuanLyNhanVien);

        jpnQuanLyNhanVien2.setBackground(new java.awt.Color(0, 0, 0));

        lblMaNhaVien.setForeground(new java.awt.Color(255, 255, 255));
        lblMaNhaVien.setText("Mã Nhân Viên");

        lblSex.setForeground(new java.awt.Color(255, 255, 255));
        lblSex.setText("Giới Tính");

        lblTenNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        lblTenNhanVien.setText("Tên Nhân Viên");

        txtMaNhanVien.setEditable(false);
        txtMaNhanVien.setBackground(new java.awt.Color(51, 51, 51));
        txtMaNhanVien.setForeground(new java.awt.Color(153, 255, 255));

        txtTenNhanVien.setBackground(new java.awt.Color(0, 0, 0));
        txtTenNhanVien.setForeground(new java.awt.Color(153, 255, 255));
        txtTenNhanVien.setCaretColor(new java.awt.Color(0, 255, 255));

        lblQuanLyNhanVien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblQuanLyNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        lblQuanLyNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/NOTEPAD.png"))); // NOI18N
        lblQuanLyNhanVien.setText("Quản Lý Nhân Viên");

        txtBirthday.setBackground(new java.awt.Color(0, 0, 0));
        txtBirthday.setForeground(new java.awt.Color(153, 255, 255));
        txtBirthday.setCaretColor(new java.awt.Color(0, 255, 255));

        txtAddress.setBackground(new java.awt.Color(0, 0, 0));
        txtAddress.setForeground(new java.awt.Color(153, 255, 255));
        txtAddress.setCaretColor(new java.awt.Color(0, 255, 255));

        lblBirthday.setForeground(new java.awt.Color(255, 255, 255));
        lblBirthday.setText("Ngày Sinh");

        lblAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblAddress.setText("Địa Chỉ");

        lblSoCMND.setForeground(new java.awt.Color(255, 255, 255));
        lblSoCMND.setText("Số CMND");

        txtSoCMND.setBackground(new java.awt.Color(0, 0, 0));
        txtSoCMND.setForeground(new java.awt.Color(153, 255, 255));
        txtSoCMND.setCaretColor(new java.awt.Color(0, 255, 255));

        txtPhone.setBackground(new java.awt.Color(0, 0, 0));
        txtPhone.setForeground(new java.awt.Color(153, 255, 255));
        txtPhone.setCaretColor(new java.awt.Color(0, 255, 255));

        lblPhone.setForeground(new java.awt.Color(255, 255, 255));
        lblPhone.setText("Số Điện Thoại");

        lblDateStart.setForeground(new java.awt.Color(255, 255, 255));
        lblDateStart.setText("Ngày Vào Làm");

        txtDateStart.setBackground(new java.awt.Color(0, 0, 0));
        txtDateStart.setForeground(new java.awt.Color(153, 255, 255));
        txtDateStart.setCaretColor(new java.awt.Color(0, 255, 255));

        lblPosition.setForeground(new java.awt.Color(255, 255, 255));
        lblPosition.setText("Chức Vụ");

        lblTool.setForeground(new java.awt.Color(153, 255, 255));
        lblTool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/TOOL.png"))); // NOI18N
        lblTool.setText("TOOL");

        btnInsert.setBackground(new java.awt.Color(0, 0, 0));
        btnInsert.setForeground(new java.awt.Color(204, 255, 255));
        btnInsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/them.png"))); // NOI18N
        btnInsert.setText("Thêm");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(0, 0, 0));
        btnDelete.setForeground(new java.awt.Color(204, 255, 255));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/xoa.png"))); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(0, 0, 0));
        btnUpdate.setForeground(new java.awt.Color(204, 255, 255));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sua.png"))); // NOI18N
        btnUpdate.setText("Sửa");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(0, 0, 0));
        btnReset.setForeground(new java.awt.Color(204, 255, 255));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/taomoi.png"))); // NOI18N
        btnReset.setText("Tạo Mới");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        txtSearch.setBackground(new java.awt.Color(0, 0, 0));
        txtSearch.setForeground(new java.awt.Color(0, 255, 255));
        txtSearch.setCaretColor(new java.awt.Color(0, 255, 255));
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        lblSearch.setBackground(new java.awt.Color(0, 0, 0));
        lblSearch.setForeground(new java.awt.Color(153, 255, 255));
        lblSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/tim.png"))); // NOI18N
        lblSearch.setText("Tìm Kiếm");

        cbbPosition.setBackground(new java.awt.Color(0, 0, 0));
        cbbPosition.setForeground(new java.awt.Color(153, 255, 255));
        cbbPosition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbPosition.setPreferredSize(new java.awt.Dimension(56, 23));

        RdoBtnMale.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(RdoBtnMale);
        RdoBtnMale.setForeground(new java.awt.Color(255, 255, 255));
        RdoBtnMale.setSelected(true);
        RdoBtnMale.setText("Nam");

        RdoBtnFemale.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(RdoBtnFemale);
        RdoBtnFemale.setForeground(new java.awt.Color(255, 255, 255));
        RdoBtnFemale.setText("Nữ");

        javax.swing.GroupLayout jpnQuanLyNhanVien2Layout = new javax.swing.GroupLayout(jpnQuanLyNhanVien2);
        jpnQuanLyNhanVien2.setLayout(jpnQuanLyNhanVien2Layout);
        jpnQuanLyNhanVien2Layout.setHorizontalGroup(
            jpnQuanLyNhanVien2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQuanLyNhanVien2Layout.createSequentialGroup()
                .addGap(348, 348, 348)
                .addComponent(lblQuanLyNhanVien)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpnQuanLyNhanVien2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jpnQuanLyNhanVien2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnQuanLyNhanVien2Layout.createSequentialGroup()
                        .addGroup(jpnQuanLyNhanVien2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMaNhaVien)
                            .addComponent(lblTenNhanVien)
                            .addComponent(lblSex)
                            .addComponent(lblBirthday)
                            .addComponent(lblAddress))
                        .addGap(26, 26, 26)
                        .addGroup(jpnQuanLyNhanVien2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpnQuanLyNhanVien2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtBirthday, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtTenNhanVien, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtMaNhanVien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpnQuanLyNhanVien2Layout.createSequentialGroup()
                                .addComponent(RdoBtnMale)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RdoBtnFemale))))
                    .addGroup(jpnQuanLyNhanVien2Layout.createSequentialGroup()
                        .addComponent(lblTool)
                        .addGap(26, 26, 26)
                        .addComponent(btnInsert)
                        .addGap(2, 2, 2)
                        .addComponent(btnDelete)
                        .addGap(2, 2, 2)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReset)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jpnQuanLyNhanVien2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSoCMND)
                    .addComponent(lblPhone)
                    .addComponent(lblDateStart)
                    .addComponent(lblPosition))
                .addGap(26, 26, 26)
                .addGroup(jpnQuanLyNhanVien2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDateStart)
                    .addComponent(txtPhone)
                    .addComponent(txtSoCMND, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(cbbPosition, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSearch)
                    .addComponent(txtSearch))
                .addGap(22, 22, 22))
        );
        jpnQuanLyNhanVien2Layout.setVerticalGroup(
            jpnQuanLyNhanVien2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQuanLyNhanVien2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblQuanLyNhanVien)
                .addGap(50, 50, 50)
                .addGroup(jpnQuanLyNhanVien2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnQuanLyNhanVien2Layout.createSequentialGroup()
                        .addGroup(jpnQuanLyNhanVien2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMaNhaVien))
                        .addGap(12, 12, 12)
                        .addGroup(jpnQuanLyNhanVien2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTenNhanVien))
                        .addGap(12, 12, 12)
                        .addGroup(jpnQuanLyNhanVien2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSex)
                            .addComponent(RdoBtnMale)
                            .addComponent(RdoBtnFemale))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpnQuanLyNhanVien2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBirthday)))
                    .addGroup(jpnQuanLyNhanVien2Layout.createSequentialGroup()
                        .addGroup(jpnQuanLyNhanVien2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSoCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSoCMND))
                        .addGap(12, 12, 12)
                        .addGroup(jpnQuanLyNhanVien2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPhone))
                        .addGap(12, 12, 12)
                        .addGroup(jpnQuanLyNhanVien2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDateStart, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDateStart))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpnQuanLyNhanVien2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbbPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPosition))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnQuanLyNhanVien2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jpnQuanLyNhanVien2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnQuanLyNhanVien2Layout.createSequentialGroup()
                        .addComponent(lblSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnQuanLyNhanVien2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTool)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jpnQuanLyNhanVien2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jpnQuanLyNhanVien2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpnQuanLyNhanVien1Layout = new javax.swing.GroupLayout(jpnQuanLyNhanVien1);
        jpnQuanLyNhanVien1.setLayout(jpnQuanLyNhanVien1Layout);
        jpnQuanLyNhanVien1Layout.setHorizontalGroup(
            jpnQuanLyNhanVien1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQuanLyNhanVien1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        jpnQuanLyNhanVien1Layout.setVerticalGroup(
            jpnQuanLyNhanVien1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQuanLyNhanVien1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenuQuanLyNhanVien.setBackground(new java.awt.Color(0, 0, 0));
        jMenuQuanLyNhanVien.setForeground(new java.awt.Color(255, 255, 255));

        jMenuHome.setForeground(new java.awt.Color(0, 255, 255));
        jMenuHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/HOME20.png"))); // NOI18N
        jMenuHome.setText("Home");
        jMenuHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuHomeMouseClicked(evt);
            }
        });
        jMenuQuanLyNhanVien.add(jMenuHome);

        jMenuSystem.setForeground(new java.awt.Color(255, 255, 255));
        jMenuSystem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/SETTINGS20.png"))); // NOI18N
        jMenuSystem.setText("Hệ thống");
        jMenuQuanLyNhanVien.add(jMenuSystem);

        jMenuSetting.setForeground(new java.awt.Color(255, 255, 255));
        jMenuSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/TOOL20.png"))); // NOI18N
        jMenuSetting.setText("Cài đặt");
        jMenuQuanLyNhanVien.add(jMenuSetting);

        jMenuHelf.setForeground(new java.awt.Color(255, 255, 255));
        jMenuHelf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/HELF20.png"))); // NOI18N
        jMenuHelf.setText("Trợ giúp");
        jMenuQuanLyNhanVien.add(jMenuHelf);

        jMenuInfo.setForeground(new java.awt.Color(0, 255, 0));
        jMenuInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/INFO20.png"))); // NOI18N
        jMenuInfo.setText("Giới thiệu");
        jMenuInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuInfoMouseClicked(evt);
            }
        });
        jMenuQuanLyNhanVien.add(jMenuInfo);

        jMenuLogOut.setForeground(new java.awt.Color(255, 0, 0));
        jMenuLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/POWER - SHUT DOWN20.png"))); // NOI18N
        jMenuLogOut.setText("Đăng xuất");
        jMenuLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuLogOutMouseClicked(evt);
            }
        });
        jMenuQuanLyNhanVien.add(jMenuLogOut);

        setJMenuBar(jMenuQuanLyNhanVien);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnQuanLyNhanVien1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnQuanLyNhanVien1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuLogOutMouseClicked
        frmDangNhap frm = new frmDangNhap();
        frm.show();
        this.dispose();
    }//GEN-LAST:event_jMenuLogOutMouseClicked

    private void jMenuHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuHomeMouseClicked
        frmQuanLy frm = new frmQuanLy();
        frm.show();
        this.dispose();
    }//GEN-LAST:event_jMenuHomeMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        LayDuLieu();
        Combobox();
    }//GEN-LAST:event_formWindowOpened

    private void tblQuanLyNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblQuanLyNhanVienMouseClicked
        int ViTriDong = tblQuanLyNhanVien.getSelectedRow();
        txtMaNhanVien.setText(tblQuanLyNhanVien.getValueAt(ViTriDong, 0).toString());
        txtTenNhanVien.setText(tblQuanLyNhanVien.getValueAt(ViTriDong, 1).toString());
        txtBirthday.setText(tblQuanLyNhanVien.getValueAt(ViTriDong, 3).toString());
        txtAddress.setText(tblQuanLyNhanVien.getValueAt(ViTriDong, 4).toString());
        txtSoCMND.setText(tblQuanLyNhanVien.getValueAt(ViTriDong, 5).toString().trim());
        txtPhone.setText(tblQuanLyNhanVien.getValueAt(ViTriDong, 6).toString().trim());
        txtDateStart.setText(tblQuanLyNhanVien.getValueAt(ViTriDong, 7).toString());
        String ChucVu = tblQuanLyNhanVien.getValueAt(ViTriDong, 8).toString();
        setSelectedCombobox(ChucVu);
        String GioiTinh = tblQuanLyNhanVien.getValueAt(ViTriDong, 2).toString();
        if (GioiTinh.equals("Nam")) {
            RdoBtnMale.setSelected(true);
        } else {
            RdoBtnFemale.setSelected(true);
        }
    }//GEN-LAST:event_tblQuanLyNhanVienMouseClicked

    private void tblQuanLyNhanVienKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblQuanLyNhanVienKeyReleased
        int ViTriDong = tblQuanLyNhanVien.getSelectedRow();
        txtMaNhanVien.setText(tblQuanLyNhanVien.getValueAt(ViTriDong, 0).toString());
        txtTenNhanVien.setText(tblQuanLyNhanVien.getValueAt(ViTriDong, 1).toString());
        txtBirthday.setText(tblQuanLyNhanVien.getValueAt(ViTriDong, 3).toString());
        txtAddress.setText(tblQuanLyNhanVien.getValueAt(ViTriDong, 4).toString());
        txtSoCMND.setText(tblQuanLyNhanVien.getValueAt(ViTriDong, 5).toString());
        txtPhone.setText(tblQuanLyNhanVien.getValueAt(ViTriDong, 6).toString());
        txtDateStart.setText(tblQuanLyNhanVien.getValueAt(ViTriDong, 7).toString());
        String ChucVu = tblQuanLyNhanVien.getValueAt(ViTriDong, 8).toString();
        setSelectedCombobox(ChucVu);
        String GioiTinh = tblQuanLyNhanVien.getValueAt(ViTriDong, 2).toString();
        if (GioiTinh.equals("Nam")) {
            RdoBtnMale.setSelected(true);
        } else {
            RdoBtnFemale.setSelected(true);
        }
    }//GEN-LAST:event_tblQuanLyNhanVienKeyReleased

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        String Search = txtSearch.getText();
        String CauTruyVan = "Select * from NhanVien "
                + "Where TenNhanVien like N'%" + Search + "%' or DiaChi like N'%" + Search + "%' "
                + "or SoCMND = '" + Search + "' or SDT = '" + Search + "'";
        ResultSet rs = Duongnxpk00662.ConnectDB.ExcuteQueryGetTable(CauTruyVan);
        Object[] obj = new Object[]{"Mã Nhân Viên", "Tên Nhân Viên", "Giới Tính", "Ngày Sinh", "Địa Chỉ",
            "Số CMND", "Số Điện Thoại", "Ngày Vào Làm", "Chức Vụ"};
        DefaultTableModel TableModel = new DefaultTableModel(obj, 0);
        tblQuanLyNhanVien.setModel(TableModel);

        try {
            while (rs.next()) {
                Object[] item = new Object[9];
                item[0] = rs.getInt("MaNhanVien");
                item[1] = rs.getString("TenNhanVien");
                item[2] = LayGioiTinhDuaVaoMa(rs.getString("GioiTinh"));
                item[3] = rs.getString("NgaySinh");
                item[4] = rs.getString("DiaChi");
                item[5] = rs.getString("SoCMND");
                item[6] = rs.getString("SDT");
                item[7] = rs.getString("NgayVaoLam");
                item[8] = LayTenChucVuDuaVaoMaChucVu(rs.getString("MaChucVu"));
                TableModel.addRow(item);
            }
        } catch (SQLException ex) {
            ThongBao("Lỗi Lấy Dữ Liệu!\n" + ex.toString());
        }
    }//GEN-LAST:event_txtSearchKeyReleased

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        String TenNhanVien = txtTenNhanVien.getText();
        String NgaySinh = txtBirthday.getText();
        String DiaChi = txtAddress.getText();
        String SoCMND = txtSoCMND.getText();
        String SDT = txtPhone.getText();
        String NgayVaoLam = txtDateStart.getText();
        int GioiTinh = 1;

        Object[] obj = cbbPosition.getSelectedObjects();
        displaycbbmodel item = (displaycbbmodel) obj[0];
        String ChucVu = item.DisplayValue.toString();

        if (TenNhanVien.equals("")) {
            ThongBao("Tên nhân viên không được để trống!");
        } else if (Duongnxpk00662.KiemTra.KiemTraCoChuaSoKhong(TenNhanVien)) {
            ThongBao("Tên nhân viên không được chứa số!");
        } else if (TenNhanVien.length() < 6) {
            ThongBao("Tên nhân viên phải lớn hơn 5 ký tự");
        } else if (NgaySinh.equals("")) {
            ThongBao("Ngày sinh không được để trống!");
        } else if (!Duongnxpk00662.KiemTra.KiemTraCoChuaSoKhong(NgaySinh)) {
            ThongBao("Ngày sinh bắt buộc phải là số!");
        } else if (!Duongnxpk00662.KiemTra.KiemTraDate(NgaySinh)) {
            ThongBao("Lỗi cú pháp!\nĐiền theo mẫu sau: Năm/Tháng/Ngày\nVí Dụ: 2016/05/31");
        } else if (DiaChi.equals("")) {
            ThongBao("Địa chỉ không được để trống");
        } else if (SoCMND.equals("")) {
            ThongBao("Số CMND không được để trống!");
        } else if (Duongnxpk00662.KiemTra.KiemTraWhitespace(SoCMND)) {
            ThongBao("Số CMND không được nhập khoảng trắng!");
        } else if (!Duongnxpk00662.KiemTra.KiemTraCoChuaSoKhong(SoCMND)) {
            ThongBao("Số CMND bắt buộc phải là số!");
        } else if (SoCMND.length() < 9 || SoCMND.length() > 12) {
            ThongBao("Số CMND phải từ 9-12 chữ số!");
        } else if (NgayVaoLam.equals("")) {
            ThongBao("Ngày vào làm không được để trống!");
        } else if (!Duongnxpk00662.KiemTra.KiemTraCoChuaSoKhong(NgayVaoLam)) {
            ThongBao("Ngày vào làm bắt buộc phải là số!");
        } else if (!Duongnxpk00662.KiemTra.KiemTraDate(NgayVaoLam)) {
            ThongBao("Lỗi cú pháp!\nĐiền theo mẫu sau: Năm/Tháng/Ngày\nVí Dụ: 2016/05/31");
        } else if (SDT.equals("") && RdoBtnFemale.isSelected() == true) {
            GioiTinh = 0;
            String CauTruyVan = "insert into NhanVien "
                    + "values (N'" + TenNhanVien + "','" + GioiTinh + "','" + NgaySinh + "',N'" + DiaChi + "',"
                    + "'" + SoCMND + "','" + SDT + "','" + NgayVaoLam + "','" + ChucVu + "')";
            Duongnxpk00662.ConnectDB.ExcuteQueryUpdateDB(CauTruyVan);
            LayDuLieu();
        } else if (SDT.equals("") && RdoBtnFemale.isSelected() == false) {
            String CauTruyVan = "insert into NhanVien "
                    + "values (N'" + TenNhanVien + "','" + GioiTinh + "','" + NgaySinh + "',N'" + DiaChi + "',"
                    + "'" + SoCMND + "','" + SDT + "','" + NgayVaoLam + "','" + ChucVu + "')";
            Duongnxpk00662.ConnectDB.ExcuteQueryUpdateDB(CauTruyVan);
            LayDuLieu();
        } else if (!Duongnxpk00662.KiemTra.KiemTraCoChuaSoKhong(SDT)) {
            ThongBao("Số điện thoại bắt buộc phải là số!");
        } else if (SDT.length() < 10 || SDT.length() > 11) {
            ThongBao("Số điện thoại phải từ 10-11 chữ số!");
        } else if (!SDT.equals("") && RdoBtnFemale.isSelected() == true) {
            GioiTinh = 0;
            String CauTruyVan = "insert into NhanVien "
                    + "values (N'" + TenNhanVien + "','" + GioiTinh + "','" + NgaySinh + "',N'" + DiaChi + "',"
                    + "'" + SoCMND + "','" + SDT + "','" + NgayVaoLam + "','" + ChucVu + "')";
            Duongnxpk00662.ConnectDB.ExcuteQueryUpdateDB(CauTruyVan);
            LayDuLieu();
        } else {
            String CauTruyVan = "insert into NhanVien "
                    + "values (N'" + TenNhanVien + "','" + GioiTinh + "','" + NgaySinh + "',N'" + DiaChi + "',"
                    + "'" + SoCMND + "','" + SDT + "','" + NgayVaoLam + "','" + ChucVu + "')";
            Duongnxpk00662.ConnectDB.ExcuteQueryUpdateDB(CauTruyVan);
            LayDuLieu();
        }


    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int[] MangViTri = tblQuanLyNhanVien.getSelectedRows();
        for (int i = 0; i < MangViTri.length; i++) {
            String MaNhanVien = tblQuanLyNhanVien.getValueAt(MangViTri[i], 0).toString();
            String CauTruyVan = "Delete from NhanVien where MaNhanVien = " + MaNhanVien;
            Duongnxpk00662.ConnectDB.ExcuteQueryUpdateDB(CauTruyVan);
        }
        LayDuLieu();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        String MaNhanVien = txtMaNhanVien.getText();
        String TenNhanVien = txtTenNhanVien.getText();
        String NgaySinh = txtBirthday.getText();
        String DiaChi = txtAddress.getText();
        String SoCMND = txtSoCMND.getText();
        String SDT = txtPhone.getText();
        String NgayVaoLam = txtDateStart.getText();
        int GioiTinh = 1;

        Object[] obj = cbbPosition.getSelectedObjects();
        displaycbbmodel item = (displaycbbmodel) obj[0];
        String ChucVu = item.DisplayValue.toString();

        if (TenNhanVien.equals("")) {
            ThongBao("Tên nhân viên không được để trống!");
        } else if (Duongnxpk00662.KiemTra.KiemTraCoChuaSoKhong(TenNhanVien)) {
            ThongBao("Tên nhân viên không được chứa số!");
        } else if (TenNhanVien.length() < 6) {
            ThongBao("Tên nhân viên phải lớn hơn 5 ký tự");
        } else if (NgaySinh.equals("")) {
            ThongBao("Ngày sinh không được để trống!");
        } else if (!Duongnxpk00662.KiemTra.KiemTraCoChuaSoKhong(NgaySinh)) {
            ThongBao("Ngày sinh bắt buộc phải là số!");
        } else if (!Duongnxpk00662.KiemTra.KiemTraDate(NgaySinh)) {
            ThongBao("Lỗi cú pháp!\nĐiền theo mẫu sau: Năm/Tháng/Ngày\nVí Dụ: 2016/05/31");
        } else if (DiaChi.equals("")) {
            ThongBao("Địa chỉ không được để trống");
        } else if (SoCMND.equals("")) {
            ThongBao("Số CMND không được để trống!");
        } else if (Duongnxpk00662.KiemTra.KiemTraWhitespace(SoCMND)) {
            ThongBao("Số CMND không được nhập khoảng trắng!");
        } else if (!Duongnxpk00662.KiemTra.KiemTraCoChuaSoKhong(SoCMND)) {
            ThongBao("Số CMND bắt buộc phải là số!");
        } else if (SoCMND.length() < 9 || SoCMND.length() > 12) {
            ThongBao("Số CMND phải từ 9-12 chữ số!");
        } else if (NgayVaoLam.equals("")) {
            ThongBao("Ngày vào làm không được để trống!");
        } else if (!Duongnxpk00662.KiemTra.KiemTraCoChuaSoKhong(NgayVaoLam)) {
            ThongBao("Ngày vào làm bắt buộc phải là số!");
        } else if (!Duongnxpk00662.KiemTra.KiemTraDate(NgayVaoLam)) {
            ThongBao("Lỗi cú pháp!\nĐiền theo mẫu sau: Năm/Tháng/Ngày\nVí Dụ: 2016/05/31");
        } else if (SDT.equals("") && RdoBtnFemale.isSelected() == true) {
            GioiTinh = 0;
            String CauTruyVan = "Update NhanVien "
                    + "Set TenNhanVien = N'" + TenNhanVien + "', GioiTinh = '" + GioiTinh + "', NgaySinh = '" + NgaySinh + "',"
                    + " DiaChi = N'" + DiaChi + "', SoCMND = '" + SoCMND + "', SDT = '" + SDT + "', NgayVaoLam = '" + NgayVaoLam + "', MaChucVu = " + ChucVu
                    + " Where MaNhanVien = " + MaNhanVien;
            Duongnxpk00662.ConnectDB.ExcuteQueryUpdateDB(CauTruyVan);
            LayDuLieu();
        } else if (SDT.equals("") && RdoBtnFemale.isSelected() == false) {
            String CauTruyVan = "Update NhanVien "
                    + "Set TenNhanVien = N'" + TenNhanVien + "', GioiTinh = '" + GioiTinh + "', NgaySinh = '" + NgaySinh + "',"
                    + " DiaChi = N'" + DiaChi + "', SoCMND = '" + SoCMND + "', SDT = '" + SDT + "', NgayVaoLam = '" + NgayVaoLam + "', MaChucVu = " + ChucVu
                    + " Where MaNhanVien = " + MaNhanVien;
            Duongnxpk00662.ConnectDB.ExcuteQueryUpdateDB(CauTruyVan);
            LayDuLieu();
        } else if (!Duongnxpk00662.KiemTra.KiemTraCoChuaSoKhong(SDT)) {
            ThongBao("Số điện thoại bắt buộc phải là số!");
        } else if (SDT.length() < 10 || SDT.length() > 11) {
            ThongBao("Số điện thoại phải từ 10-11 chữ số!");
        } else if (!SDT.equals("") && RdoBtnFemale.isSelected() == true) {
            GioiTinh = 0;
            String CauTruyVan = "Update NhanVien "
                    + "Set TenNhanVien = N'" + TenNhanVien + "', GioiTinh = '" + GioiTinh + "', NgaySinh = '" + NgaySinh + "',"
                    + " DiaChi = N'" + DiaChi + "', SoCMND = '" + SoCMND + "', SDT = '" + SDT + "', NgayVaoLam = '" + NgayVaoLam + "', MaChucVu = " + ChucVu
                    + " Where MaNhanVien = " + MaNhanVien;
            Duongnxpk00662.ConnectDB.ExcuteQueryUpdateDB(CauTruyVan);
            LayDuLieu();
        } else {
            String CauTruyVan = "Update NhanVien "
                    + "Set TenNhanVien = N'" + TenNhanVien + "', GioiTinh = '" + GioiTinh + "', NgaySinh = '" + NgaySinh + "',"
                    + " DiaChi = N'" + DiaChi + "', SoCMND = '" + SoCMND + "', SDT = '" + SDT + "', NgayVaoLam = '" + NgayVaoLam + "', MaChucVu = " + ChucVu
                    + " Where MaNhanVien = " + MaNhanVien;
            Duongnxpk00662.ConnectDB.ExcuteQueryUpdateDB(CauTruyVan);
            LayDuLieu();

        }


    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtMaNhanVien.setText("");
        txtTenNhanVien.setText("");
        RdoBtnMale.setSelected(true);
        txtBirthday.setText("");
        txtAddress.setText("");
        txtSoCMND.setText("");
        txtPhone.setText("");
        txtDateStart.setText("");
        cbbPosition.setSelectedIndex(3);
        txtSearch.setText("");
        LayDuLieu();
    }//GEN-LAST:event_btnResetActionPerformed

    private void jMenuInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuInfoMouseClicked
        frmInfo frm = new frmInfo();
        frm.show();
    }//GEN-LAST:event_jMenuInfoMouseClicked

    private void LayDuLieu() {
        String CauTruyVan = "Select * from NhanVien";
        ResultSet rs = Duongnxpk00662.ConnectDB.ExcuteQueryGetTable(CauTruyVan);

        Object[] obj = new Object[]{"Mã Nhân Viên", "Tên Nhân Viên", "Giới Tính", "Ngày Sinh", "Địa Chỉ",
            "Số CMND", "Số Điện Thoại", "Ngày Vào Làm", "Chức Vụ"};
        DefaultTableModel TableModel = new DefaultTableModel(obj, 0);
        tblQuanLyNhanVien.setModel(TableModel);

        try {
            while (rs.next()) {
                Object[] item = new Object[9];
                item[0] = rs.getInt("MaNhanVien");
                item[1] = rs.getString("TenNhanVien");
                item[2] = LayGioiTinhDuaVaoMa(rs.getString("GioiTinh"));
                item[3] = rs.getString("NgaySinh");
                item[4] = rs.getString("DiaChi");
                item[5] = rs.getString("SoCMND");
                item[6] = rs.getString("SDT");
                item[7] = rs.getString("NgayVaoLam");
                item[8] = LayTenChucVuDuaVaoMaChucVu(rs.getString("MaChucVu"));
                TableModel.addRow(item);
            }
        } catch (SQLException ex) {
            ThongBao("Lỗi Lấy Dữ Liệu!\n" + ex.toString());
        }
    }

    //Display ComboBoxModel
    private void setSelectedCombobox(String ChucVu) {
        for (int i = 0; i < cbbPosition.getItemCount(); i++) {
            Object obj = cbbPosition.getItemAt(i);

            if (obj != null) {
                displaycbbmodel m = (displaycbbmodel) obj;
                if (ChucVu.equals(m.DisplayMember)) {
                    cbbPosition.setSelectedItem(m);
                }
            }
        }
    }

    private void Combobox() {
        String ctv = "Select * from ChucVu";
        ResultSet rs = Duongnxpk00662.ConnectDB.ExcuteQueryGetTable(ctv);
        DefaultComboBoxModel cbbModel = new DefaultComboBoxModel();
        try {
            while (rs.next()) {
                displaycbbmodel item = new displaycbbmodel(rs.getString("TenChucVu"), rs.getInt("MaChucVu"));
                cbbModel.addElement(item);
            }
            cbbPosition.setModel(cbbModel);
        } catch (Exception e) {
            ThongBao("Lỗi ComboBox!" + e);
        }
    }

    private String LayTenChucVuDuaVaoMaChucVu(String MaChucVu) {
        String TenChucVu = "";

        String ctv = "select TenChucVu from ChucVu where MaChucVu = " + MaChucVu;
        ResultSet rs = Duongnxpk00662.ConnectDB.ExcuteQueryGetTable(ctv);
        try {
            while (rs.next()) {
                TenChucVu = rs.getString("TenChucVu");
            }
        } catch (SQLException ex) {
            ThongBao("Error!\n" + ex);
        }

        return TenChucVu;
    }

    //Giới Tính
    private String LayGioiTinhDuaVaoMa(String MaGioiTinh) {
        String GioiTinh = "";

        String ctv = "select GioiTinh from GioiTinh where MaGioiTinh = " + MaGioiTinh;
        ResultSet rs = Duongnxpk00662.ConnectDB.ExcuteQueryGetTable(ctv);
        try {
            while (rs.next()) {
                GioiTinh = rs.getString("GioiTinh");
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }

        return GioiTinh;
    }

    //Thông báo DiaLog
    private void ThongBao(String NoiDungThongBao) {
        JOptionPane.showMessageDialog(this, NoiDungThongBao);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmQuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmQuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmQuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmQuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmQuanLyNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RdoBtnFemale;
    private javax.swing.JRadioButton RdoBtnMale;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbbPosition;
    private javax.swing.JMenu jMenuHelf;
    private javax.swing.JMenu jMenuHome;
    private javax.swing.JMenu jMenuInfo;
    private javax.swing.JMenu jMenuLogOut;
    private javax.swing.JMenuBar jMenuQuanLyNhanVien;
    private javax.swing.JMenu jMenuSetting;
    private javax.swing.JMenu jMenuSystem;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpnQuanLyNhanVien1;
    private javax.swing.JPanel jpnQuanLyNhanVien2;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblBirthday;
    private javax.swing.JLabel lblDateStart;
    private javax.swing.JLabel lblMaNhaVien;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPosition;
    private javax.swing.JLabel lblQuanLyNhanVien;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblSex;
    private javax.swing.JLabel lblSoCMND;
    private javax.swing.JLabel lblTenNhanVien;
    private javax.swing.JLabel lblTool;
    private javax.swing.JTable tblQuanLyNhanVien;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtBirthday;
    private javax.swing.JTextField txtDateStart;
    private javax.swing.JTextField txtMaNhanVien;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSoCMND;
    private javax.swing.JTextField txtTenNhanVien;
    // End of variables declaration//GEN-END:variables
}
