/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.Dimension;
import java.awt.Graphics;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DuongAli
 */
public class frmQuanLyKhachHang extends javax.swing.JFrame {

    String string = "src\\images\\QuanLyKhachHang.png";

    /**
     * Creates new form frmQuanLyKhachHang
     */
    public frmQuanLyKhachHang() {
        initComponents();
        getRootPane().setDefaultButton(btnSearch);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jpnQuanLyKhachHang1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblQuanLyKhachhang = new javax.swing.JTable();
        jpnQuanLyKhachHang2 = new javax.swing.JPanel(){
            ImageIcon icon = new ImageIcon(string);
            public void paintComponent(Graphics g) {
                Dimension d = this.getSize();
                g.drawImage(icon.getImage(),0,0,d.width,d.height,null);
                setOpaque(false);
                super.paintComponent(g); }
        };
        lblPhone = new javax.swing.JLabel();
        lblMaKhachHang = new javax.swing.JLabel();
        lblSex = new javax.swing.JLabel();
        lblTenKhachHang = new javax.swing.JLabel();
        txtMaKhachHang = new javax.swing.JTextField();
        txtTenKhachHang = new javax.swing.JTextField();
        lblQuanLyKhachHang = new javax.swing.JLabel();
        txtBirthday = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        lblBirthday = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        RdoBtnMale = new javax.swing.JRadioButton();
        RdoBtnFemale = new javax.swing.JRadioButton();
        lblTool = new javax.swing.JLabel();
        btnInsert = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jMenuQuanLyKhachHang = new javax.swing.JMenuBar();
        jMenuHome = new javax.swing.JMenu();
        jMenuSystem = new javax.swing.JMenu();
        jMenuSetting = new javax.swing.JMenu();
        jMenuHelf = new javax.swing.JMenu();
        jMenuInfo = new javax.swing.JMenu();
        jMenuLogOut = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jpnQuanLyKhachHang1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        tblQuanLyKhachhang.setBackground(new java.awt.Color(0, 0, 0));
        tblQuanLyKhachhang.setForeground(new java.awt.Color(51, 255, 255));
        tblQuanLyKhachhang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Khách Hàng", "Tên Khách Hàng", "Giới Tính", "Ngày Sinh", "Đia Chỉ", "Số Điện Thoại"
            }
        ));
        tblQuanLyKhachhang.setSelectionBackground(new java.awt.Color(222, 222, 222));
        tblQuanLyKhachhang.setSelectionForeground(new java.awt.Color(22, 22, 22));
        tblQuanLyKhachhang.setShowVerticalLines(false);
        tblQuanLyKhachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblQuanLyKhachhangMouseClicked(evt);
            }
        });
        tblQuanLyKhachhang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblQuanLyKhachhangKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblQuanLyKhachhang);
        if (tblQuanLyKhachhang.getColumnModel().getColumnCount() > 0) {
            tblQuanLyKhachhang.getColumnModel().getColumn(0).setResizable(false);
            tblQuanLyKhachhang.getColumnModel().getColumn(0).setPreferredWidth(15);
            tblQuanLyKhachhang.getColumnModel().getColumn(1).setResizable(false);
            tblQuanLyKhachhang.getColumnModel().getColumn(1).setPreferredWidth(100);
            tblQuanLyKhachhang.getColumnModel().getColumn(2).setResizable(false);
            tblQuanLyKhachhang.getColumnModel().getColumn(2).setPreferredWidth(15);
            tblQuanLyKhachhang.getColumnModel().getColumn(3).setResizable(false);
            tblQuanLyKhachhang.getColumnModel().getColumn(3).setPreferredWidth(25);
            tblQuanLyKhachhang.getColumnModel().getColumn(4).setResizable(false);
            tblQuanLyKhachhang.getColumnModel().getColumn(4).setPreferredWidth(150);
        }

        jpnQuanLyKhachHang2.setBackground(new java.awt.Color(0, 0, 0));

        lblPhone.setForeground(new java.awt.Color(255, 255, 255));
        lblPhone.setText("Số Điện Thoại");

        lblMaKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        lblMaKhachHang.setText("Mã Khách Hàng");

        lblSex.setForeground(new java.awt.Color(255, 255, 255));
        lblSex.setText("Giới Tính");

        lblTenKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        lblTenKhachHang.setText("Tên Khách Hàng");

        txtMaKhachHang.setEditable(false);
        txtMaKhachHang.setBackground(new java.awt.Color(51, 51, 51));
        txtMaKhachHang.setForeground(new java.awt.Color(51, 255, 255));

        txtTenKhachHang.setBackground(new java.awt.Color(0, 0, 0));
        txtTenKhachHang.setForeground(new java.awt.Color(51, 255, 255));
        txtTenKhachHang.setCaretColor(new java.awt.Color(51, 255, 255));

        lblQuanLyKhachHang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblQuanLyKhachHang.setForeground(new java.awt.Color(51, 255, 255));
        lblQuanLyKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/NOTEPAD.png"))); // NOI18N
        lblQuanLyKhachHang.setText("Quản Lý Khách Hàng");

        txtBirthday.setBackground(new java.awt.Color(0, 0, 0));
        txtBirthday.setForeground(new java.awt.Color(51, 255, 255));
        txtBirthday.setCaretColor(new java.awt.Color(51, 255, 255));

        txtAddress.setBackground(new java.awt.Color(0, 0, 0));
        txtAddress.setForeground(new java.awt.Color(51, 255, 255));
        txtAddress.setCaretColor(new java.awt.Color(51, 255, 255));

        lblBirthday.setForeground(new java.awt.Color(255, 255, 255));
        lblBirthday.setText("Ngày Sinh");

        lblAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblAddress.setText("Địa Chỉ");

        txtPhone.setBackground(new java.awt.Color(0, 0, 0));
        txtPhone.setForeground(new java.awt.Color(51, 255, 255));
        txtPhone.setCaretColor(new java.awt.Color(51, 255, 255));

        RdoBtnMale.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(RdoBtnMale);
        RdoBtnMale.setForeground(new java.awt.Color(255, 255, 255));
        RdoBtnMale.setSelected(true);
        RdoBtnMale.setText("Nam");

        RdoBtnFemale.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(RdoBtnFemale);
        RdoBtnFemale.setForeground(new java.awt.Color(255, 255, 255));
        RdoBtnFemale.setText("Nữ");

        lblTool.setForeground(new java.awt.Color(153, 255, 255));
        lblTool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/TOOL.png"))); // NOI18N
        lblTool.setText("TOOL");

        btnInsert.setBackground(new java.awt.Color(0, 0, 0));
        btnInsert.setForeground(new java.awt.Color(204, 255, 255));
        btnInsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/them.png"))); // NOI18N
        btnInsert.setText("Thêm");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(0, 0, 0));
        btnDelete.setForeground(new java.awt.Color(204, 255, 255));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/xoa.png"))); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(0, 0, 0));
        btnUpdate.setForeground(new java.awt.Color(204, 255, 255));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sua.png"))); // NOI18N
        btnUpdate.setText("Sửa");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(0, 0, 0));
        btnReset.setForeground(new java.awt.Color(204, 255, 255));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/taomoi.png"))); // NOI18N
        btnReset.setText("Tạo Mới");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnSearch.setBackground(new java.awt.Color(0, 0, 0));
        btnSearch.setForeground(new java.awt.Color(204, 255, 255));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/tim.png"))); // NOI18N
        btnSearch.setText("Tìm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        txtSearch.setBackground(new java.awt.Color(0, 0, 0));
        txtSearch.setForeground(new java.awt.Color(0, 255, 255));
        txtSearch.setCaretColor(new java.awt.Color(51, 255, 255));

        javax.swing.GroupLayout jpnQuanLyKhachHang2Layout = new javax.swing.GroupLayout(jpnQuanLyKhachHang2);
        jpnQuanLyKhachHang2.setLayout(jpnQuanLyKhachHang2Layout);
        jpnQuanLyKhachHang2Layout.setHorizontalGroup(
            jpnQuanLyKhachHang2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQuanLyKhachHang2Layout.createSequentialGroup()
                .addGroup(jpnQuanLyKhachHang2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnQuanLyKhachHang2Layout.createSequentialGroup()
                        .addGap(354, 354, 354)
                        .addComponent(lblQuanLyKhachHang))
                    .addGroup(jpnQuanLyKhachHang2Layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addGroup(jpnQuanLyKhachHang2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpnQuanLyKhachHang2Layout.createSequentialGroup()
                                .addGroup(jpnQuanLyKhachHang2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPhone, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblMaKhachHang, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblTenKhachHang, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblSex, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblBirthday, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblAddress, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(26, 26, 26)
                                .addGroup(jpnQuanLyKhachHang2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpnQuanLyKhachHang2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jpnQuanLyKhachHang2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtBirthday)
                                            .addComponent(txtTenKhachHang)
                                            .addComponent(txtMaKhachHang)
                                            .addComponent(txtAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jpnQuanLyKhachHang2Layout.createSequentialGroup()
                                        .addComponent(RdoBtnMale)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(RdoBtnFemale))))
                            .addGroup(jpnQuanLyKhachHang2Layout.createSequentialGroup()
                                .addComponent(lblTool)
                                .addGap(26, 26, 26)
                                .addGroup(jpnQuanLyKhachHang2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jpnQuanLyKhachHang2Layout.createSequentialGroup()
                                        .addComponent(btnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpnQuanLyKhachHang2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(214, Short.MAX_VALUE))
        );
        jpnQuanLyKhachHang2Layout.setVerticalGroup(
            jpnQuanLyKhachHang2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQuanLyKhachHang2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblQuanLyKhachHang)
                .addGap(40, 40, 40)
                .addGroup(jpnQuanLyKhachHang2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaKhachHang))
                .addGap(12, 12, 12)
                .addGroup(jpnQuanLyKhachHang2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTenKhachHang))
                .addGap(12, 12, 12)
                .addGroup(jpnQuanLyKhachHang2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSex)
                    .addComponent(RdoBtnMale)
                    .addComponent(RdoBtnFemale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnQuanLyKhachHang2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBirthday))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnQuanLyKhachHang2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnQuanLyKhachHang2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jpnQuanLyKhachHang2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTool))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnQuanLyKhachHang2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jpnQuanLyKhachHang2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jpnQuanLyKhachHang2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jpnQuanLyKhachHang1Layout = new javax.swing.GroupLayout(jpnQuanLyKhachHang1);
        jpnQuanLyKhachHang1.setLayout(jpnQuanLyKhachHang1Layout);
        jpnQuanLyKhachHang1Layout.setHorizontalGroup(
            jpnQuanLyKhachHang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQuanLyKhachHang1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        jpnQuanLyKhachHang1Layout.setVerticalGroup(
            jpnQuanLyKhachHang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQuanLyKhachHang1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenuQuanLyKhachHang.setBackground(new java.awt.Color(0, 0, 0));
        jMenuQuanLyKhachHang.setForeground(new java.awt.Color(255, 255, 255));

        jMenuHome.setForeground(new java.awt.Color(0, 255, 255));
        jMenuHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/HOME20.png"))); // NOI18N
        jMenuHome.setText("Home");
        jMenuHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuHomeMouseClicked(evt);
            }
        });
        jMenuQuanLyKhachHang.add(jMenuHome);

        jMenuSystem.setForeground(new java.awt.Color(255, 255, 255));
        jMenuSystem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/SETTINGS20.png"))); // NOI18N
        jMenuSystem.setText("Hệ thống");
        jMenuQuanLyKhachHang.add(jMenuSystem);

        jMenuSetting.setForeground(new java.awt.Color(255, 255, 255));
        jMenuSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/TOOL20.png"))); // NOI18N
        jMenuSetting.setText("Cài đặt");
        jMenuQuanLyKhachHang.add(jMenuSetting);

        jMenuHelf.setForeground(new java.awt.Color(255, 255, 255));
        jMenuHelf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/HELF20.png"))); // NOI18N
        jMenuHelf.setText("Trợ giúp");
        jMenuQuanLyKhachHang.add(jMenuHelf);

        jMenuInfo.setForeground(new java.awt.Color(0, 255, 0));
        jMenuInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/INFO20.png"))); // NOI18N
        jMenuInfo.setText("Giới thiệu");
        jMenuInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuInfoMouseClicked(evt);
            }
        });
        jMenuQuanLyKhachHang.add(jMenuInfo);

        jMenuLogOut.setForeground(new java.awt.Color(255, 0, 0));
        jMenuLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/POWER - SHUT DOWN20.png"))); // NOI18N
        jMenuLogOut.setText("Đăng xuất");
        jMenuLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuLogOutMouseClicked(evt);
            }
        });
        jMenuQuanLyKhachHang.add(jMenuLogOut);

        setJMenuBar(jMenuQuanLyKhachHang);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnQuanLyKhachHang1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnQuanLyKhachHang1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuLogOutMouseClicked
        frmDangNhap frm = new frmDangNhap();
        frm.show();
        this.dispose();
    }//GEN-LAST:event_jMenuLogOutMouseClicked

    private void jMenuHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuHomeMouseClicked
        frmQuanLy frm = new frmQuanLy();
        frm.show();
        this.dispose();
    }//GEN-LAST:event_jMenuHomeMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        LayDuLieu();
    }//GEN-LAST:event_formWindowOpened

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        String TenKhachHang = txtTenKhachHang.getText();
        String NgaySinh = txtBirthday.getText();
        String DiaChi = txtAddress.getText();
        String SDT = txtPhone.getText();
        int GioiTinh = 1;

        if (TenKhachHang.equals("")) {
            ThongBao("Tên khách hàng không được để trống!");
        } else if (Duongnxpk00662.KiemTra.KiemTraCoChuaSoKhong(TenKhachHang)) {
            ThongBao("Tên khách hàng không được chứa số!");
        } else if (TenKhachHang.length() < 6) {
            ThongBao("Tên khách hàng phải lớn hơn 5 ký tự");
        } else if (NgaySinh.equals("")) {
            ThongBao("Ngày sinh không được để trống!");
        } else if (!Duongnxpk00662.KiemTra.KiemTraCoChuaSoKhong(NgaySinh)) {
            ThongBao("Ngày sinh bắt buộc phải là số!");
        } else if (!Duongnxpk00662.KiemTra.KiemTraDate(NgaySinh)) {
            ThongBao("Lỗi cú pháp!\nĐiền theo mẫu sau: Năm/Tháng/Ngày\nVí Dụ: 2016/12/31");
        } else if (DiaChi.equals("")) {
            ThongBao("Địa chỉ không được để trống");
        } else if (SDT.equals("") && RdoBtnFemale.isSelected() == true) {
            GioiTinh = 0;
            String CauTruyVan = "insert into KhachHang "
                    + "values (N'" + TenKhachHang + "','" + GioiTinh + "','" + NgaySinh + "',N'" + DiaChi + "','" + SDT + "')";
            Duongnxpk00662.ConnectDB.ExcuteQueryUpdateDB(CauTruyVan);
            LayDuLieu();
        } else if (SDT.equals("") && RdoBtnFemale.isSelected() == false) {
            String CauTruyVan = "insert into KhachHang "
                    + "values (N'" + TenKhachHang + "','" + GioiTinh + "','" + NgaySinh + "',N'" + DiaChi + "','" + SDT + "')";
            Duongnxpk00662.ConnectDB.ExcuteQueryUpdateDB(CauTruyVan);
            LayDuLieu();
        } else if (!Duongnxpk00662.KiemTra.KiemTraCoChuaSoKhong(SDT)) {
            ThongBao("Số điện thoại bắt buộc phải là số!");
        } else if (SDT.length() < 10 || SDT.length() > 11) {
            ThongBao("Số điện thoại phải từ 10-11 chữ số!");
        } else if (!SDT.equals("") && RdoBtnFemale.isSelected() == true) {
            GioiTinh = 0;
            String CauTruyVan = "insert into KhachHang "
                    + "values (N'" + TenKhachHang + "','" + GioiTinh + "','" + NgaySinh + "',N'" + DiaChi + "','" + SDT + "')";
            Duongnxpk00662.ConnectDB.ExcuteQueryUpdateDB(CauTruyVan);
            LayDuLieu();
        } else {
            String CauTruyVan = "insert into KhachHang "
                    + "values (N'" + TenKhachHang + "','" + GioiTinh + "','" + NgaySinh + "',N'" + DiaChi + "','" + SDT + "')";
            Duongnxpk00662.ConnectDB.ExcuteQueryUpdateDB(CauTruyVan);
            LayDuLieu();
        }
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int[] MangViTri = tblQuanLyKhachhang.getSelectedRows();
        for (int i = 0; i < MangViTri.length; i++) {
            String MaKhachHang = tblQuanLyKhachhang.getValueAt(MangViTri[i], 0).toString();
            String CauTruyVan = "Delete from KhachHang where MaKhachHang =" + MaKhachHang;
            Duongnxpk00662.ConnectDB.ExcuteQueryUpdateDB(CauTruyVan);
        }
        LayDuLieu();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        String TenKhachHang = txtTenKhachHang.getText();
        String NgaySinh = txtBirthday.getText();
        String DiaChi = txtAddress.getText();
        String SDT = txtPhone.getText();
        String MaKhachHang = txtMaKhachHang.getText();
        int GioiTinh = 1;

        if (TenKhachHang.equals("") || NgaySinh.equals("") || DiaChi.equals("")) {
            ThongBao("Bạn Hãy Nhập Đầy Đủ Dữ Liệu!");
        } else if (TenKhachHang.equals("")) {
            ThongBao("Tên khách hàng không được để trống!");
        } else if (!Duongnxpk00662.KiemTra.KiemTraCoChuaChuKhong(TenKhachHang)) {
            ThongBao("Tên khách hàng không được chứa số!");
        } else if (TenKhachHang.length() < 6) {
            ThongBao("Tên khách hàng phải lớn hơn 5 ký tự");
        } else if (NgaySinh.equals("")) {
            ThongBao("Ngày sinh không được để trống!");
        } else if (!Duongnxpk00662.KiemTra.KiemTraCoChuaSoKhong(NgaySinh)) {
            ThongBao("Ngày sinh bắt buộc phải là số!");
        } else if (!Duongnxpk00662.KiemTra.KiemTraDate(NgaySinh)) {
            ThongBao("Lỗi cú pháp!\nĐiền theo mẫu sau: Năm/Tháng/Ngày\nVí Dụ: 2016/12/31");
        } else if (DiaChi.equals("")) {
            ThongBao("Địa chỉ không được để trống");
        } else if (SDT.equals("") && RdoBtnFemale.isSelected() == true) {
            String CauTruyVan = "Update KhachHang "
                    + "Set TenKhachHang = N'" + TenKhachHang + "', GioiTinh = 0 , NgaySinh = '" + NgaySinh + "', DiaChi = N'" + DiaChi + "',SDT=" + SDT
                    + "Where MaKhachHang = " + MaKhachHang;
            Duongnxpk00662.ConnectDB.ExcuteQueryUpdateDB(CauTruyVan);
            LayDuLieu();
        } else if (SDT.equals("") && RdoBtnFemale.isSelected() == false) {
            String CauTruyVan = "Update KhachHang "
                    + "Set TenKhachHang = N'" + TenKhachHang + "', GioiTinh = 1 , NgaySinh = '" + NgaySinh + "', DiaChi = N'" + DiaChi + "',SDT=" + SDT
                    + "Where MaKhachHang = " + MaKhachHang;
            Duongnxpk00662.ConnectDB.ExcuteQueryUpdateDB(CauTruyVan);
            LayDuLieu();
        } else if (!Duongnxpk00662.KiemTra.KiemTraCoChuaSoKhong(SDT)) {
            ThongBao("Số điện thoại bắt buộc phải là số!");
        } else if (SDT.length() < 10 || SDT.length() > 11) {
            ThongBao("Số điện thoại phải từ 10-11 chữ số!");
        } else if (!SDT.equals("") && RdoBtnFemale.isSelected() == true) {
            String CauTruyVan = "Update KhachHang "
                    + "Set TenKhachHang = N'" + TenKhachHang + "', GioiTinh = 0 , NgaySinh = '" + NgaySinh + "', DiaChi = N'" + DiaChi + "',SDT=" + SDT
                    + "Where MaKhachHang = " + MaKhachHang;
            Duongnxpk00662.ConnectDB.ExcuteQueryUpdateDB(CauTruyVan);
            LayDuLieu();
        } else {
            String CauTruyVan = "Update KhachHang "
                    + "Set TenKhachHang = N'" + TenKhachHang + "', GioiTinh = 1 , NgaySinh = '" + NgaySinh + "', DiaChi = N'" + DiaChi + "',SDT=" + SDT
                    + "Where MaKhachHang = " + MaKhachHang;
            Duongnxpk00662.ConnectDB.ExcuteQueryUpdateDB(CauTruyVan);
            LayDuLieu();
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tblQuanLyKhachhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblQuanLyKhachhangMouseClicked
        int ViTriDong = tblQuanLyKhachhang.getSelectedRow();
        txtMaKhachHang.setText(tblQuanLyKhachhang.getValueAt(ViTriDong, 0).toString());
        txtTenKhachHang.setText(tblQuanLyKhachhang.getValueAt(ViTriDong, 1).toString());
        txtBirthday.setText(tblQuanLyKhachhang.getValueAt(ViTriDong, 3).toString());
        txtAddress.setText(tblQuanLyKhachhang.getValueAt(ViTriDong, 4).toString());
        txtPhone.setText(tblQuanLyKhachhang.getValueAt(ViTriDong, 5).toString());
        String GioiTinh = tblQuanLyKhachhang.getValueAt(ViTriDong, 2).toString();
        if (GioiTinh.equals("Nam")) {
            RdoBtnMale.setSelected(true);
        } else {
            RdoBtnFemale.setSelected(true);
        }
    }//GEN-LAST:event_tblQuanLyKhachhangMouseClicked

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtMaKhachHang.setText("");
        txtTenKhachHang.setText("");
        txtBirthday.setText("");
        txtAddress.setText("");
        txtPhone.setText("");
        txtSearch.setText("");
        RdoBtnMale.setSelected(true);
        LayDuLieu();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String Search = txtSearch.getText();
        String CauTruyVan = "Select * from KhachHang "
                + "Where TenKhachHang like N'%" + Search + "%' or DiaChi like N'%" + Search + "%' or SDT = '" + Search + "'";

        if (!Search.equals("")) {
            ResultSet rs = Duongnxpk00662.ConnectDB.ExcuteQueryGetTable(CauTruyVan);
            Object[] obj = new Object[]{"Mã Khách Hàng", "Tên Khách Hàng", "Giới Tính", "Ngày Sinh", "Địa Chỉ", "Số Điện Thoại"};
            DefaultTableModel TableModel = new DefaultTableModel(obj, 0);
            tblQuanLyKhachhang.setModel(TableModel);

            try {
                while (rs.next()) {
                    Object[] item = new Object[6];
                    item[0] = rs.getInt("MaKhachHang");
                    item[1] = rs.getString("TenKhachHang");
                    item[2] = rs.getString("GioiTinh");
                    item[3] = rs.getString("NgaySinh");
                    item[4] = rs.getString("DiaChi");
                    item[5] = rs.getString("SDT");
                    TableModel.addRow(item);
                }
            } catch (SQLException ex) {
                ThongBao("Lỗi Lấy Dữ Liệu!\n" + ex.toString());
            }
        } else {
            ThongBao("Bạn Muốn Tìm Gì?\nHãy Nhập Vào Ô Tìm Kiếm ^^!");
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void tblQuanLyKhachhangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblQuanLyKhachhangKeyReleased
        int ViTriDong = tblQuanLyKhachhang.getSelectedRow();
        txtMaKhachHang.setText(tblQuanLyKhachhang.getValueAt(ViTriDong, 0).toString());
        txtTenKhachHang.setText(tblQuanLyKhachhang.getValueAt(ViTriDong, 1).toString());
        txtBirthday.setText(tblQuanLyKhachhang.getValueAt(ViTriDong, 3).toString());
        txtAddress.setText(tblQuanLyKhachhang.getValueAt(ViTriDong, 4).toString());
        txtPhone.setText(tblQuanLyKhachhang.getValueAt(ViTriDong, 5).toString());
        String GioiTinh = tblQuanLyKhachhang.getValueAt(ViTriDong, 2).toString();
        if (GioiTinh.equals("Nam")) {
            RdoBtnMale.setSelected(true);
        } else {
            RdoBtnFemale.setSelected(true);
        }
    }//GEN-LAST:event_tblQuanLyKhachhangKeyReleased

    private void jMenuInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuInfoMouseClicked
        frmInfo frm = new frmInfo();
        frm.show();
    }//GEN-LAST:event_jMenuInfoMouseClicked

    private void LayDuLieu() {
        String CauTruyVan = "Select * from KhachHang";
        ResultSet rs = Duongnxpk00662.ConnectDB.ExcuteQueryGetTable(CauTruyVan);

        Object[] obj = new Object[]{"Mã Khách Hàng", "Tên Khách Hàng", "Giới Tính", "Ngày Sinh", "Địa Chỉ", "Số Điện Thoại"};
        DefaultTableModel TableModel = new DefaultTableModel(obj, 0);
        tblQuanLyKhachhang.setModel(TableModel);

        try {
            while (rs.next()) {
                Object[] item = new Object[6];
                item[0] = rs.getInt("MaKhachHang");
                item[1] = rs.getString("TenKhachHang");
                item[2] = LayGioiTinhDuaVaoMa(rs.getString("GioiTinh"));
                item[3] = rs.getString("NgaySinh");
                item[4] = rs.getString("DiaChi");
                item[5] = rs.getString("SDT");
                TableModel.addRow(item);
            }
        } catch (SQLException ex) {
            ThongBao("Lỗi Lấy Dữ Liệu!\n" + ex.toString());
        }
    }

    private String LayGioiTinhDuaVaoMa(String MaGioiTinh) {
        String GioiTinh = "";

        String ctv = "select GioiTinh from GioiTinh where MaGioiTinh = " + MaGioiTinh;
        ResultSet rs = Duongnxpk00662.ConnectDB.ExcuteQueryGetTable(ctv);
        try {
            while (rs.next()) {
                GioiTinh = rs.getString("GioiTinh");
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }

        return GioiTinh;
    }

    //Thông báo DiaLog
    private void ThongBao(String NoiDungThongBao) {
        JOptionPane.showMessageDialog(this, NoiDungThongBao);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmQuanLyKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmQuanLyKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmQuanLyKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmQuanLyKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmQuanLyKhachHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RdoBtnFemale;
    private javax.swing.JRadioButton RdoBtnMale;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenu jMenuHelf;
    private javax.swing.JMenu jMenuHome;
    private javax.swing.JMenu jMenuInfo;
    private javax.swing.JMenu jMenuLogOut;
    private javax.swing.JMenuBar jMenuQuanLyKhachHang;
    private javax.swing.JMenu jMenuSetting;
    private javax.swing.JMenu jMenuSystem;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpnQuanLyKhachHang1;
    private javax.swing.JPanel jpnQuanLyKhachHang2;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblBirthday;
    private javax.swing.JLabel lblMaKhachHang;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblQuanLyKhachHang;
    private javax.swing.JLabel lblSex;
    private javax.swing.JLabel lblTenKhachHang;
    private javax.swing.JLabel lblTool;
    private javax.swing.JTable tblQuanLyKhachhang;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtBirthday;
    private javax.swing.JTextField txtMaKhachHang;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTenKhachHang;
    // End of variables declaration//GEN-END:variables
}
