/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author DuongAli
 */
public class frmQuanLy extends javax.swing.JFrame {
    String string = "src\\images\\QuanLy.jpg";
    /**
     * Creates new form frmQuanLy
     */
    public frmQuanLy() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnQuanLy1 = new javax.swing.JPanel();
        jpnQuanLy2 = new javax.swing.JPanel(){
            ImageIcon icon = new ImageIcon(string);
            public void paintComponent(Graphics g) {
                Dimension d = this.getSize();
                g.drawImage(icon.getImage(),0,0,d.width,d.height,null);
                setOpaque(false);
                super.paintComponent(g); }
        };
        lblQuanLy = new javax.swing.JLabel();
        btnAccount = new javax.swing.JButton();
        btnNhanVien = new javax.swing.JButton();
        btnKhachHang = new javax.swing.JButton();
        btnSanPham = new javax.swing.JButton();
        btnLoaiSanPham = new javax.swing.JButton();
        lblShowInfo = new javax.swing.JLabel();
        lblShowAccess = new javax.swing.JLabel();
        lblShowUser = new javax.swing.JLabel();
        jMenuQuanLy = new javax.swing.JMenuBar();
        jMenuSystem = new javax.swing.JMenu();
        jMenuSetting = new javax.swing.JMenu();
        jMenuHelf = new javax.swing.JMenu();
        jMenuInfo = new javax.swing.JMenu();
        jMenuLogOut = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jpnQuanLy1.setBackground(new java.awt.Color(0, 0, 0));

        jpnQuanLy2.setBackground(new java.awt.Color(0, 0, 0));
        jpnQuanLy2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        lblQuanLy.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblQuanLy.setForeground(new java.awt.Color(255, 255, 255));
        lblQuanLy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/HOME.png"))); // NOI18N
        lblQuanLy.setText(" Quản Lý");

        btnAccount.setBackground(new java.awt.Color(0, 0, 0));
        btnAccount.setForeground(new java.awt.Color(153, 255, 255));
        btnAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/User1.png"))); // NOI18N
        btnAccount.setText("Tài Khoản");
        btnAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountActionPerformed(evt);
            }
        });

        btnNhanVien.setBackground(new java.awt.Color(0, 0, 0));
        btnNhanVien.setForeground(new java.awt.Color(153, 255, 255));
        btnNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/nhanvien64.png"))); // NOI18N
        btnNhanVien.setText("Nhân Viên");
        btnNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanVienActionPerformed(evt);
            }
        });

        btnKhachHang.setBackground(new java.awt.Color(0, 0, 0));
        btnKhachHang.setForeground(new java.awt.Color(153, 255, 255));
        btnKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/members.png"))); // NOI18N
        btnKhachHang.setText("Khách Hàng");
        btnKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhachHangActionPerformed(evt);
            }
        });

        btnSanPham.setBackground(new java.awt.Color(0, 0, 0));
        btnSanPham.setForeground(new java.awt.Color(153, 255, 255));
        btnSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/giohang.png"))); // NOI18N
        btnSanPham.setText("Sản Phẩm");
        btnSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSanPhamActionPerformed(evt);
            }
        });

        btnLoaiSanPham.setBackground(new java.awt.Color(0, 0, 0));
        btnLoaiSanPham.setForeground(new java.awt.Color(153, 255, 255));
        btnLoaiSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/kinhlup.png"))); // NOI18N
        btnLoaiSanPham.setText("Loại Sản Phẩm");
        btnLoaiSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoaiSanPhamActionPerformed(evt);
            }
        });

        lblShowInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/MESSENGER - YAHOO.png"))); // NOI18N
        lblShowInfo.setText("Hiển Thị THông Báo!");

        lblShowAccess.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/XNVIEW.png"))); // NOI18N
        lblShowAccess.setText("Hiển Thị Lượt Truy Cập!");

        lblShowUser.setForeground(new java.awt.Color(0, 255, 255));
        lblShowUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/MESSENGER - MSN.png"))); // NOI18N
        lblShowUser.setText("Hiển Thị USER! NGUYỄN DƯƠNG");

        javax.swing.GroupLayout jpnQuanLy2Layout = new javax.swing.GroupLayout(jpnQuanLy2);
        jpnQuanLy2.setLayout(jpnQuanLy2Layout);
        jpnQuanLy2Layout.setHorizontalGroup(
            jpnQuanLy2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQuanLy2Layout.createSequentialGroup()
                .addGroup(jpnQuanLy2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnQuanLy2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpnQuanLy2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblShowUser, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(lblShowAccess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblShowInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50))
                    .addGroup(jpnQuanLy2Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(lblQuanLy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jpnQuanLy2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnQuanLy2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnNhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnKhachHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSanPham, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLoaiSanPham, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAccount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jpnQuanLy2Layout.setVerticalGroup(
            jpnQuanLy2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnQuanLy2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnQuanLy2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAccount)
                    .addGroup(jpnQuanLy2Layout.createSequentialGroup()
                        .addComponent(lblShowInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblShowAccess, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNhanVien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnQuanLy2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKhachHang)
                    .addComponent(lblQuanLy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnQuanLy2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnQuanLy2Layout.createSequentialGroup()
                        .addComponent(btnSanPham)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLoaiSanPham)
                        .addContainerGap())
                    .addComponent(lblShowUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btnNhanVien.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout jpnQuanLy1Layout = new javax.swing.GroupLayout(jpnQuanLy1);
        jpnQuanLy1.setLayout(jpnQuanLy1Layout);
        jpnQuanLy1Layout.setHorizontalGroup(
            jpnQuanLy1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQuanLy1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnQuanLy2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnQuanLy1Layout.setVerticalGroup(
            jpnQuanLy1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnQuanLy1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnQuanLy2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenuQuanLy.setBackground(new java.awt.Color(0, 0, 0));

        jMenuSystem.setForeground(new java.awt.Color(255, 255, 255));
        jMenuSystem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/TOOL.png"))); // NOI18N
        jMenuSystem.setText("Hệ thống");
        jMenuQuanLy.add(jMenuSystem);

        jMenuSetting.setForeground(new java.awt.Color(255, 255, 255));
        jMenuSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/SETTINGS.png"))); // NOI18N
        jMenuSetting.setText("Cài đặt");
        jMenuQuanLy.add(jMenuSetting);

        jMenuHelf.setForeground(new java.awt.Color(255, 255, 255));
        jMenuHelf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/HELF.png"))); // NOI18N
        jMenuHelf.setText("Trợ giúp");
        jMenuQuanLy.add(jMenuHelf);

        jMenuInfo.setForeground(new java.awt.Color(0, 255, 0));
        jMenuInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/INFO.png"))); // NOI18N
        jMenuInfo.setText("Giới thiệu");
        jMenuInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuInfoMouseClicked(evt);
            }
        });
        jMenuQuanLy.add(jMenuInfo);

        jMenuLogOut.setForeground(new java.awt.Color(255, 0, 0));
        jMenuLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/POWER - SHUT DOWN.png"))); // NOI18N
        jMenuLogOut.setText("Đăng xuất");
        jMenuLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuLogOutMouseClicked(evt);
            }
        });
        jMenuQuanLy.add(jMenuLogOut);

        setJMenuBar(jMenuQuanLy);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnQuanLy1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnQuanLy1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountActionPerformed
        frmQuanLyTaiKhoan frm = new frmQuanLyTaiKhoan();
        frm.show();
        this.dispose();
    }//GEN-LAST:event_btnAccountActionPerformed

    private void btnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanVienActionPerformed
        frmQuanLyNhanVien frm = new frmQuanLyNhanVien();
        frm.show();
        this.dispose();
    }//GEN-LAST:event_btnNhanVienActionPerformed

    private void btnKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhachHangActionPerformed
        frmQuanLyKhachHang frm = new frmQuanLyKhachHang();
        frm.show();
        this.dispose();
    }//GEN-LAST:event_btnKhachHangActionPerformed

    private void btnSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSanPhamActionPerformed
        frmQuanLySanPham frm = new frmQuanLySanPham();
        frm.show();
        this.dispose();
    }//GEN-LAST:event_btnSanPhamActionPerformed

    private void btnLoaiSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoaiSanPhamActionPerformed
        frmQuanLyLoaiSanPham frm = new frmQuanLyLoaiSanPham();
        frm.show();
        this.dispose();
    }//GEN-LAST:event_btnLoaiSanPhamActionPerformed

    private void jMenuLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuLogOutMouseClicked
        frmDangNhap frm = new frmDangNhap();
        frm.show();
        this.dispose();
    }//GEN-LAST:event_jMenuLogOutMouseClicked

    private void jMenuInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuInfoMouseClicked
        frmInfo frm = new frmInfo();
        frm.show();
    }//GEN-LAST:event_jMenuInfoMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        lblShowUser.setText("Đăng nhập bằng tài khoản:  " + Duongnxpk00662.HienThiUserName);
        lblShowAccess.setText("Lượt đăng nhập:  " +Duongnxpk00662.LuotDangNhap);
        
        if(frmDangNhap.Quyen == 1){
            lblShowInfo.setText("Bạn vừa đăng nhập bằng quyền ADMIN");
        }
        else if(frmDangNhap.Quyen == 2){
            lblShowInfo.setText("Bạn vừa đăng nhập bằng quyền IT");
        }
        else if(frmDangNhap.Quyen == 3){
            lblShowInfo.setText("Bạn vừa đăng nhập bằng quyền Nhân Viên");
            btnAccount.setEnabled(false);
            btnNhanVien.setEnabled(false);
        }
        else if(frmDangNhap.Quyen == 4){
            lblShowInfo.setText("Bạn vừa đăng nhập bằng quyền Khách Hàng");
            btnAccount.setEnabled(false);
            btnNhanVien.setEnabled(false);
            btnKhachHang.setEnabled(false);
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmQuanLy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccount;
    private javax.swing.JButton btnKhachHang;
    private javax.swing.JButton btnLoaiSanPham;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JButton btnSanPham;
    private javax.swing.JMenu jMenuHelf;
    private javax.swing.JMenu jMenuInfo;
    private javax.swing.JMenu jMenuLogOut;
    private javax.swing.JMenuBar jMenuQuanLy;
    private javax.swing.JMenu jMenuSetting;
    private javax.swing.JMenu jMenuSystem;
    private javax.swing.JPanel jpnQuanLy1;
    private javax.swing.JPanel jpnQuanLy2;
    private javax.swing.JLabel lblQuanLy;
    private javax.swing.JLabel lblShowAccess;
    private javax.swing.JLabel lblShowInfo;
    private javax.swing.JLabel lblShowUser;
    // End of variables declaration//GEN-END:variables
}
