/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package duongnxpk00662;

import java.awt.Dimension;
import java.awt.Graphics;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author DuongAli
 */
public class frmDangNhap extends javax.swing.JFrame {

    String string = "src\\images\\7.jpg";

    /**
     * Creates new form DangNhap
     */
    public frmDangNhap() {
        initComponents();
        getRootPane().setDefaultButton(btnDangNhap);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jplLogin = new javax.swing.JPanel(){
            ImageIcon icon = new ImageIcon(string);
            public void paintComponent(Graphics g) {
                Dimension d = this.getSize();
                g.drawImage(icon.getImage(),0,0,d.width,d.height,null);
                setOpaque(false);
                super.paintComponent(g); }
        };
        lblUserName = new javax.swing.JLabel();
        lblPassWord = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        txtPassWord = new javax.swing.JPasswordField();
        btnDangNhap = new javax.swing.JButton();
        btnDangKy = new javax.swing.JButton();
        lblDangNhap = new javax.swing.JLabel();
        cbxLogin = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jplLogin.setBackground(new java.awt.Color(0, 0, 0));

        lblUserName.setForeground(new java.awt.Color(255, 255, 255));
        lblUserName.setText("Tên Đăng Nhập");

        lblPassWord.setForeground(new java.awt.Color(255, 255, 255));
        lblPassWord.setText("Mật Khẩu");

        txtUserName.setForeground(new java.awt.Color(0, 0, 153));
        txtUserName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        txtPassWord.setForeground(new java.awt.Color(0, 0, 153));
        txtPassWord.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        btnDangNhap.setBackground(new java.awt.Color(0, 0, 0));
        btnDangNhap.setForeground(new java.awt.Color(255, 255, 255));
        btnDangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btnlogin.png"))); // NOI18N
        btnDangNhap.setText("Đăng Nhập");
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });

        btnDangKy.setBackground(new java.awt.Color(0, 0, 0));
        btnDangKy.setForeground(new java.awt.Color(255, 255, 255));
        btnDangKy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dangky.png"))); // NOI18N
        btnDangKy.setText("Đăng Ký");
        btnDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangKyActionPerformed(evt);
            }
        });

        lblDangNhap.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDangNhap.setForeground(new java.awt.Color(153, 255, 255));
        lblDangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/KEY.png"))); // NOI18N
        lblDangNhap.setText(" ĐĂNG NHẬP");

        cbxLogin.setBackground(new java.awt.Color(0, 0, 0));
        cbxLogin.setForeground(new java.awt.Color(153, 255, 255));
        cbxLogin.setText("Remember me");

        javax.swing.GroupLayout jplLoginLayout = new javax.swing.GroupLayout(jplLogin);
        jplLogin.setLayout(jplLoginLayout);
        jplLoginLayout.setHorizontalGroup(
            jplLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplLoginLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(jplLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblUserName)
                    .addComponent(lblPassWord))
                .addGap(27, 27, 27)
                .addGroup(jplLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxLogin)
                    .addComponent(lblDangNhap)
                    .addGroup(jplLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplLoginLayout.createSequentialGroup()
                            .addGroup(jplLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtUserName)
                                .addComponent(txtPassWord, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(53, 53, 53))
                        .addGroup(jplLoginLayout.createSequentialGroup()
                            .addComponent(btnDangNhap)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnDangKy)
                            .addContainerGap()))))
        );
        jplLoginLayout.setVerticalGroup(
            jplLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplLoginLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(lblDangNhap)
                .addGap(32, 32, 32)
                .addGroup(jplLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserName)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jplLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassWord)
                    .addComponent(txtPassWord, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(cbxLogin)
                .addGap(18, 18, 18)
                .addGroup(jplLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDangNhap)
                    .addComponent(btnDangKy))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jplLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jplLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKyActionPerformed
        frmDangKy frm = new frmDangKy();
        frm.show();
        this.dispose();
    }//GEN-LAST:event_btnDangKyActionPerformed

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        String TenDangNhap = txtUserName.getText().trim();
        String MatKhau = txtPassWord.getText().trim();

        if (TenDangNhap.equals("") || MatKhau.equals("")) {
            ThongBao("Bạn chưa nhập đầy đủ thông tin");
        } else if (KiemTra(TenDangNhap, MatKhau)) {
            frmQuanLy frm = new frmQuanLy();
            frm.show();
            this.dispose();
            //
            String CauTruyVan = "Update LuotDangNhap set LuotDangNhap = LuotDangNhap + 1";
            Duongnxpk00662.ConnectDB.ExcuteQueryUpdateDB(CauTruyVan);
            String ShowGiaTri = "select LuotDangNhap from LuotDangNhap";
            ResultSet rs = Duongnxpk00662.ConnectDB.ExcuteQueryGetTable(ShowGiaTri);
            try{
                while(rs.next()){
                    Duongnxpk00662.LuotDangNhap =  rs.getInt("LuotDangNhap");
                }
            }
            catch (Exception e) {
                System.out.println(e.toString());
            }
            //
            Duongnxpk00662.HienThiUserName = txtUserName.getText();
        } else {
            ThongBao("Bạn nhập sai tên đăng nhập hoặc mật khẩu!");
        }
    }//GEN-LAST:event_btnDangNhapActionPerformed

    public static int Quyen = 0;

    private boolean KiemTra(String TenDangNhap, String MatKhau) {
        boolean kq = false;

        String CauTruyVan = "Select * from TaiKhoan where TenTaiKhoan = N'" + TenDangNhap + "' and MatKhau= N'" + MatKhau + "'";
        ResultSet rs = Duongnxpk00662.ConnectDB.ExcuteQueryGetTable(CauTruyVan);

        try {
            if (rs.next()) {
                kq = true;
                Quyen = rs.getInt("MaQuyen");
            }
        } catch (SQLException ex) {
            ThongBao("Lỗi Đăng Nhập!");
        }

        return kq;
    }

    //Thông báo DiaLog
    private void ThongBao(String NoiDungThongBao) {
        JOptionPane.showMessageDialog(this, NoiDungThongBao);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDangNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangKy;
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JCheckBox cbxLogin;
    private javax.swing.JPanel jplLogin;
    private javax.swing.JLabel lblDangNhap;
    private javax.swing.JLabel lblPassWord;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JPasswordField txtPassWord;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
